//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gudochkina_pr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecyclingActs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecyclingActs()
        {
            this.ServiceOrders = new HashSet<ServiceOrders>();
        }
    
        public int ActId { get; set; }
        public int ContractId { get; set; }
        public System.DateTime ActDate { get; set; }
        public int WasteTypeId { get; set; }
        public decimal Volume { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Notes { get; set; }
    
        public virtual RecyclingContracts RecyclingContracts { get; set; }
        public virtual WasteTypes WasteTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrders> ServiceOrders { get; set; }
    }
}
