//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gudochkina_pr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceOrders()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int OrderId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> EmployeeCompletedId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Notes { get; set; }
        public Nullable<int> RecyclingActId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual RecyclingActs RecyclingActs { get; set; }
    }
}
