//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gudochkina_pr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplies()
        {
            this.SupplyItems = new HashSet<SupplyItems>();
        }
    
        public int SupplyId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyItems> SupplyItems { get; set; }
    }
}
